# Generated by Django 5.0.6 on 2024-08-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_scannedpackagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedpackagelog',
            name='status',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], default='Incoming', max_length=10),
        ),
    ]
